TradeTrust/generic-templates

README.md
- update the read me with the generic template renderer url
=> update the renderer url in the read me

.storybook/preview-head.html, application/index.tsx, package-lock.json, package.json, src/templates/coveringLetter/CoveringLetter.tsx, src/templates/coveringLetter/sample.ts, src/templates/coveringLetter/types.ts, src/templates/index.tsx, src/templates/invoice/Invoice.stories.mdx, src/templates/invoice/Invoice.test.tsx, src/templates/invoice/Invoice.tsx, src/templates/invoice/index.tsx, src/templates/invoice/sample.ts, src/templates/invoice/types.ts, static/index.html
- https://www.pivotaltracker.com/story/show/175139542
=> feat: invoice template setup

src/integration/integration.spec.ts, src/templates/coveringLetter/CoveringLetter.tsx
- bug with iframe height been set wrongly after importing tailwind library
- logo image (delay loaded) will not be accounted in setting of iframe height nevertheless
- set min-height with px, avoid vh unit
=> fix: cover letter height

package-lock.json, package.json, webpack.config.js
This PR contains a fix for the webpack settings by using https://webpack.js.org/plugins/copy-webpack-plugin/ to copy /static/images into the build directory so referenced images can be rendered:
=> fix: webpack config

src/templates/BillOfLading/BillOfLadingTemplate.tsx
- https://www.pivotaltracker.com/story/show/175475710
=> chore: remove maersk

README.md, application/index.tsx, package-lock.json, package.json, src/integration/integration.spec.ts, src/templates/BillOfLadingGeneric/BillOfLadingGenericTemplate.stories.tsx, src/templates/BillOfLadingGeneric/BillOfLadingGenericTemplate.test.tsx, src/templates/BillOfLadingGeneric/BillOfLadingGenericTemplate.tsx, src/templates/BillOfLadingGeneric/index.tsx, src/templates/BillOfLadingGeneric/sample.ts, src/templates/BillOfLadingGeneric/types.ts, src/templates/index.tsx
feat: added generic template for billOfLading
=> feat: added a generic template for BillOfLading

src/templates/ChaftaCoo/ChaftaCooTemplate.tsx
- https://www.pivotaltracker.com/story/show/176492044
- to look like the pdf
=> chore: coo look

src/templates/BillOfLading/BillOfLadingTemplate.tsx, src/templates/BillOfLading/sample.ts, src/templates/BillOfLading/types.ts
https://www.pivotaltracker.com/story/show/176714866
- To change the data field for MAEU to be editable text. If is not possible, please help to update MAEU as "SGPU"
- To change the data field for signature portion "Signed for the Carrier" to be editable text for "A.P. Moller", if is not possible, please remove the text "A.P. Moller"
Will modify generic template config file to add in editable text field
=> chore: update bl fields

application/index.tsx, src/integration/invoice.spec.ts, src/templates/Invoice/InvoiceTemplate.stories.tsx, src/templates/Invoice/InvoiceTemplate.test.tsx, src/templates/Invoice/InvoiceTemplate.tsx, src/templates/Invoice/sampleV2.ts, src/templates/Invoice/sampleV3.ts, src/templates/Invoice/types.ts
Added OA v3 compatibility for invoice template
=> feat: add v3 to invoice

src/templates/ChaftaCoo/ChaftaCooTemplate.stories.tsx, src/templates/ChaftaCoo/ChaftaCooTemplate.tsx
- https://www.pivotaltracker.com/story/show/179715462
- stray values should not appear when value is empty
- convert divs to semantic html tags
- clean up design according to actual ChAFTA COO references
=> fix: ChAFTA COO fields

src/integration/bill-of-lading.spec.ts, src/templates/BillOfLading/BillOfLadingTemplate.stories.tsx, src/templates/BillOfLading/BillOfLadingTemplate.tsx, src/templates/BillOfLading/sampleV2.ts, src/templates/BillOfLading/sampleV3.ts, src/templates/BillOfLading/types.ts
Added placeOfReceipt and placeOfDelivery as it is within the configuration schema and the document design. However the properties and usage isn't reflected in the template
=> fix: added place of receipt and place of delivery

README.md, src/core/DocumentQrCode/DocumentQrCode.tsx, src/integration/cover-letter-dbs.spec.ts, src/templates/BillOfLading/BillOfLadingTemplate.test.tsx, src/templates/BillOfLading/BillOfLadingTemplate.tsx, src/templates/BillOfLadingGeneric/BillOfLadingGenericTemplate.test.tsx, src/templates/BillOfLadingGeneric/sample.ts, src/templates/CoveringLetter/CoveringLetterTemplate.test.tsx, src/templates/CoveringLetter/sample2.ts
- import images so they get processed by `file-loader`
=> fix: import images

package-lock.json, package.json
- get latest default template https://github.com/Open-Attestation/decentralized-renderer-react-components/pull/73
=> fix: default template

package-lock.json, package.json
- get latest styled default template
=> fix: bump default template

src/core/PrivacyFilter/PrivacyFilter.tsx
- Update selective disclosure text
=> feat: update selective disclosure text

.github/workflows/ci-workflow.yml, .prettierignore, .storybook/main.js, static/index.html
- update actions
- add prettier check
=> feat: ci update

src/templates/BillOfLadingMaerskPilot/BillOfLadingMaerskPilotTemplate.tsx, src/templates/BillOfLadingMaerskPilot/sampleV2.ts, src/templates/BillOfLadingMaerskPilot/types.ts
Update maersk template for pilot
=> fix: update maersk template

README.md
typo in previous pr https://github.com/TradeTrust/generic-templates/pull/80
=> docs: readme correction

.storybook/preview-head.html, src/tailwind.css, src/templates/Brochure/BrochureTemplate.tsx, static/index.html
=> feat: add fonts

.storybook/preview-head.html, src/core/PrivacyFilter/PrivacyFilter.tsx, src/tailwind.css, src/templates/Brochure/BrochureTemplate.tsx, static/index.html
In this PR:
- Add mobile view for w3c brochure template
- Add custom fonts
=> chore: add w3c brochure mobile view

README.md
- to be abit more clear on 2 types of documents
=> docs: readme table

README.md, src/templates/BillOfLadingBimcoStandard/index.tsx, src/templates/index.tsx
added a fix so to be able to use BIMCO template
=> fix: update so to be able to use BIMCO template

application/app.tsx, application/index.tsx, package-lock.json, package.json, src/@types/window.d.ts, src/index.tsx, src/integration/invoice.spec.ts, src/templates/BillOfLading/BillOfLadingTemplate.tsx, src/templates/BillOfLadingBimcoStandard/BillOfLadingBimcoStandard.tsx, src/templates/BillOfLadingCarrierTemplate/BillOfLadingCarrierTemplate.tsx, src/templates/BillOfLadingGeneric/BillOfLadingGenericTemplate.tsx, src/templates/BillOfLadingMaerskPilot/BillOfLadingMaerskPilotTemplate.tsx, src/templates/BillOfLadingMaerskTpac/BillOfLadingMaerskTpacTemplate.tsx, src/templates/Brochure/BrochureTemplate.tsx, src/templates/CertificateOfNonManipulation/CertificateOfNonManipulationTemplate.tsx, src/templates/ChaftaCoo/ChaftaCooTemplate.tsx, src/templates/CoveringLetter/CoveringLetterTemplate.tsx, src/templates/Invoice/InvoiceTemplate.stories.tsx, src/templates/Invoice/InvoiceTemplate.test.tsx, src/templates/Invoice/InvoiceTemplate.tsx, src/templates/Invoice/sampleIDVCV4.ts, src/templates/Invoice/types.ts, src/templates/SimpleCoo/SimpleCooTemplate.tsx, src/templates/XmlRenderer/template.tsx, src/templates/index.tsx, src/utils/index.test.ts
This pr migrates the decentralised render-react components to the forked tt one.
It also adds additional tests / documents regarding an invoice issued with the IDVC method.
=> feat: migrate decentralised components

README.md, application/index.tsx, src/templates/WarehouseReceipt/WarehouseReceiptTemplate.stories.tsx, src/templates/WarehouseReceipt/WarehouseReceiptTemplate.test.tsx, src/templates/WarehouseReceipt/WarehouseReceiptTemplate.tsx, src/templates/WarehouseReceipt/index.tsx, src/templates/WarehouseReceipt/sampleV2.ts, src/templates/WarehouseReceipt/types.ts, src/templates/index.tsx
feat: warehouse receipt template
=> feat: warehouse receipt template

package-lock.json, package.json
Update deps after removing oa wording.
=> fix: upgrade deps

application/app.tsx, package-lock.json, package.json, src/integration/cover-letter-malformed.spec.ts
Updated decentralized-renderer-react-components to latest version
##Issue
[Jira Ticket](https://afa-cdi.atlassian.net/browse/TT-618?atlOrigin=eyJpIjoiZjFjNWE2NDI1MzZiNDE5NGJmZDdjOGExZTVlZDUzMTQiLCJwIjoiaiJ9)
=> chore: bump decentralized-renderer-react-components version

package-lock.json, package.json
Update decentralized-renderer-react-components to latest version
=> chore: update decentralized-renderer-react-components

src/utils/index.ts
update check for qr code url for w3c documents
=> fix: getQRCodeURL function
